# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
  # - name: Check dbs Connector Server
    # fail:
      # msg: "ERROR: No dbs Connector server found in inventory"
    # when: (groups['dbsConnectorServers'] | length == 0)
    
  - name: Install mailbox db connector Ubuntu
    become: true
    apt: name={{ item }} state=present
    with_items:
      - "{{ mailbox_dbconnectors_packages }}"
    when: 
      - ansible_os_family == "Debian"
      - inventory_hostname in groups["dbsConnectorServers"] 
      - groups['dbsConnectorServers'] | length == 1
      - groups['dbsConnectorServers'][0] == groups['postgresServers'][0]
    tags:
      - install-carbonio-dbconnectors
     
  - name: Install files db connector Ubuntu
    become: true
    apt: name={{ item }} state=present
    with_items:
      - "{{ files_dbconnectors_packages }}"
    when: 
      - ansible_os_family == "Debian"
      - inventory_hostname in groups["dbsConnectorServers"] 
      - groups['dbsConnectorServers'] | length == 1
      - groups['dbsConnectorServers'][0] == groups['postgresServers'][0]
      - groups['filesServers'] | length > 0
    tags:
      - install-carbonio-dbconnectors
      
  - name: Install docs db connector Ubuntu
    become: true
    apt: name={{ item }} state=present
    with_items:
      - "{{ docs_dbconnectors_packages }}"
    when: 
      - ansible_os_family == "Debian"
      - inventory_hostname in groups["dbsConnectorServers"] 
      - groups['dbsConnectorServers'] | length == 1
      - groups['dbsConnectorServers'][0] == groups['postgresServers'][0]
      - groups['docsServers'] | length > 0 
    tags:
      - install-carbonio-dbconnectors

  - name: Install tasks db connector Ubuntu
    become: true
    apt: name={{ item }} state=present
    with_items:
      - "{{ task_dbconnectors_packages }}"
    when: 
      - ansible_os_family == "Debian"
      - inventory_hostname in groups["dbsConnectorServers"] 
      - groups['dbsConnectorServers'] | length == 1
      - groups['dbsConnectorServers'][0] == groups['postgresServers'][0]
      - groups['taskServers'] | length > 0
    tags:
      - install-carbonio-dbconnectors

#Only if dbsConnectorServers group in inventory is wrong 
  - name: Check if dbconnectors should be installed on the same server as postgres
    debug:
      msg: "dbconnectors should be installed on the same server as Postgres starting from version 24.12.0. The inventory file does not meet this requirement. The dbsConnectorServers group will be skipped, installation will be performed on the Postgres server"
    when: 
      - ansible_os_family == "Debian" 
      - inventory_hostname in groups["dbsConnectorServers"] 
      - groups['dbsConnectorServers'] | length > 1 or (groups['dbsConnectorServers'] | length == 1 and groups['dbsConnectorServers'][0] != groups['postgresServers'][0])
    delegate_to: "{{ groups['postgresServers'][0] }}"
    tags:
      - install-carbonio-dbconnectors

  - name: Install mailbox db connector Ubuntu [Wrong dbsConnectorServers value]
    become: true
    apt: name={{ item }} state=present
    with_items:
      - "{{ mailbox_dbconnectors_packages }}"
    when: 
      - ansible_os_family == "Debian"
      - inventory_hostname in groups["dbsConnectorServers"] 
      - groups['dbsConnectorServers'] | length > 1 or (groups['dbsConnectorServers'] | length == 1 and groups['dbsConnectorServers'][0] != groups['postgresServers'][0])
    delegate_to: "{{ groups['postgresServers'][0] }}"
    tags:
      - install-carbonio-dbconnectors
     
  - name: Install files db connector Ubuntu [Wrong dbsConnectorServers value]
    become: true
    apt: name={{ item }} state=present
    with_items:
      - "{{ files_dbconnectors_packages }}"
    when: 
      - ansible_os_family == "Debian"
      - inventory_hostname in groups["dbsConnectorServers"] 
      - groups['dbsConnectorServers'] | length > 1 or (groups['dbsConnectorServers'] | length == 1 and groups['dbsConnectorServers'][0] != groups['postgresServers'][0])
      - groups['filesServers'] | length > 0
    delegate_to: "{{ groups['postgresServers'][0] }}"
    tags:
      - install-carbonio-dbconnectors
      
  - name: Install docs db connector Ubuntu [Wrong dbsConnectorServers value]
    become: true
    apt: name={{ item }} state=present
    with_items:
      - "{{ docs_dbconnectors_packages }}"
    when: 
      - ansible_os_family == "Debian"
      - inventory_hostname in groups["dbsConnectorServers"] 
      - groups['dbsConnectorServers'] | length > 1 or (groups['dbsConnectorServers'] | length == 1 and groups['dbsConnectorServers'][0] != groups['postgresServers'][0])
      - groups['docsServers'] | length > 0 
    delegate_to: "{{ groups['postgresServers'][0] }}"
    tags:
      - install-carbonio-dbconnectors

  - name: Install tasks db connector Ubuntu [Wrong dbsConnectorServers value]
    become: true
    apt: name={{ item }} state=present
    with_items:
      - "{{ task_dbconnectors_packages }}"
    when: 
      - ansible_os_family == "Debian"
      - inventory_hostname in groups["dbsConnectorServers"] 
      - groups['dbsConnectorServers'] | length > 1 or (groups['dbsConnectorServers'] | length == 1 and groups['dbsConnectorServers'][0] != groups['postgresServers'][0])
      - groups['taskServers'] | length > 0
    delegate_to: "{{ groups['postgresServers'][0] }}"
    tags:
      - install-carbonio-dbconnectors

##### RHEL
  - name: Install mailbox db connector RHEL
    become: true
    yum: name={{ item }} state=present
    with_items:
      - "{{ mailbox_dbconnectors_packages }}"
    when:
      - ansible_os_family == "RedHat" or ansible_os_family == "CentOS"
      - inventory_hostname in groups["dbsConnectorServers"]  
      - groups['dbsConnectorServers'] | length == 1
      - groups['dbsConnectorServers'][0] == groups['postgresServers'][0]
    tags:
      - install-carbonio-dbconnectors
     
  - name: Install files db connector RHEL
    become: true
    yum: name={{ item }} state=present
    with_items:
      - "{{ files_dbconnectors_packages }}"
    when:
      - ansible_os_family == "RedHat" or ansible_os_family == "CentOS"
      - inventory_hostname in groups["dbsConnectorServers"]  
      - groups['dbsConnectorServers'] | length == 1
      - groups['dbsConnectorServers'][0] == groups['postgresServers'][0]
      - groups['filesServers'] | length > 0 
    tags:
      - install-carbonio-dbconnectors
      
  - name: Install docs db connector RHEL
    become: true
    yum: name={{ item }} state=present
    with_items:
      - "{{ docs_dbconnectors_packages }}"
    when: 
      - ansible_os_family == "RedHat" or ansible_os_family == "CentOS"
      - inventory_hostname in groups["dbsConnectorServers"]  
      - groups['dbsConnectorServers'] | length == 1
      - groups['dbsConnectorServers'][0] == groups['postgresServers'][0]
      - groups['docsServers'] | length > 0
    tags:
      - install-carbonio-dbconnectors
      
  - name: Install tasks db connector RHEL
    become: true
    yum: name={{ item }} state=present
    with_items:
      - "{{ task_dbconnectors_packages }}"
    when: 
      - ansible_os_family == "RedHat" or ansible_os_family == "CentOS"
      - inventory_hostname in groups["dbsConnectorServers"]  
      - groups['dbsConnectorServers'] | length == 1
      - groups['dbsConnectorServers'][0] == groups['postgresServers'][0]
      - groups['taskServers'] | length > 0
    tags:
      - install-carbonio-dbconnectors

#Only if dbsConnectorServers group in inventory is wrong 
  - name: Check if dbconnectors should be installed on the same server as postgres
    debug:
      msg: "dbconnectors should be installed on the same server as Postgres starting from version 24.12.0. The inventory file does not meet this requirement. The dbsConnectorServers group will be skipped, installation will be performed on the Postgres server"
    when: 
      - ansible_os_family == "RedHat" or ansible_os_family == "CentOS"
      - inventory_hostname in groups["dbsConnectorServers"] 
      - groups['dbsConnectorServers'] | length > 1 or (groups['dbsConnectorServers'] | length == 1 and groups['dbsConnectorServers'][0] != groups['postgresServers'][0])
    delegate_to: "{{ groups['postgresServers'][0] }}"
    tags:
      - install-carbonio-dbconnectors

  - name: Install mailbox db connector RHEL [Wrong dbsConnectorServers value]
    become: true
    yum: name={{ item }} state=present
    with_items:
      - "{{ mailbox_dbconnectors_packages }}"
    when:
      - ansible_os_family == "RedHat" or ansible_os_family == "CentOS"
      - inventory_hostname in groups["dbsConnectorServers"]  
      - groups['dbsConnectorServers'] | length > 1 or (groups['dbsConnectorServers'] | length == 1 and groups['dbsConnectorServers'][0] != groups['postgresServers'][0])
    delegate_to: "{{ groups['postgresServers'][0] }}"
    tags:
      - install-carbonio-dbconnectors
     
  - name: Install files db connector RHEL [Wrong dbsConnectorServers value]
    become: true
    yum: name={{ item }} state=present
    with_items:
      - "{{ files_dbconnectors_packages }}"
    when:
      - ansible_os_family == "RedHat" or ansible_os_family == "CentOS"
      - inventory_hostname in groups["dbsConnectorServers"]  
      - groups['dbsConnectorServers'] | length > 1 or (groups['dbsConnectorServers'] | length == 1 and groups['dbsConnectorServers'][0] != groups['postgresServers'][0])
      - groups['filesServers'] | length > 0 
    delegate_to: "{{ groups['postgresServers'][0] }}"
    tags:
      - install-carbonio-dbconnectors
      
  - name: Install docs db connector RHEL [Wrong dbsConnectorServers value]
    become: true
    yum: name={{ item }} state=present
    with_items:
      - "{{ docs_dbconnectors_packages }}"
    when: 
      - ansible_os_family == "RedHat" or ansible_os_family == "CentOS"
      - inventory_hostname in groups["dbsConnectorServers"]  
      - groups['dbsConnectorServers'] | length > 1 or (groups['dbsConnectorServers'] | length == 1 and groups['dbsConnectorServers'][0] != groups['postgresServers'][0])
      - groups['docsServers'] | length > 0
    delegate_to: "{{ groups['postgresServers'][0] }}"
    tags:
      - install-carbonio-dbconnectors
      
  - name: Install tasks db connector RHEL [Wrong dbsConnectorServers value]
    become: true
    yum: name={{ item }} state=present
    with_items:
      - "{{ task_dbconnectors_packages }}"
    when: 
      - ansible_os_family == "RedHat" or ansible_os_family == "CentOS"
      - inventory_hostname in groups["dbsConnectorServers"]  
      - groups['dbsConnectorServers'] | length > 1 or (groups['dbsConnectorServers'] | length == 1 and groups['dbsConnectorServers'][0] != groups['postgresServers'][0])
      - groups['taskServers'] | length > 0
    delegate_to: "{{ groups['postgresServers'][0] }}"
    tags:
      - install-carbonio-dbconnectors