# SPDX-FileCopyrightText: Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
  - name: Install Carbonio task [Ubuntu]
    become: true
    ansible.builtin.apt: name={{ item }} state=present
    with_items:
      - "{{ task_packages }}"
    when: 
      - ansible_facts.os_family == "Debian"
      - inventory_hostname in groups["taskServers"] 
    tags:
      - install-carbonio-task
      
  - name: Install Carbonio task RH
    become: true
    ansible.builtin.yum: name={{ item }} state=present
    with_items:
      - "{{ task_packages }}"
    when: 
      - ansible_facts.os_family == "RedHat"
      - inventory_hostname in groups["taskServers"] 
    tags:
      - install-carbonio-task

    
     