# SPDX-FileCopyrightText: Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
  - name: Install Carbonio MTA [Ubuntu]
    become: true
    ansible.builtin.apt: name={{ item }} state=present
    with_items:
      - "{{ mta_packages }}" 
    when:
      - ansible_facts.os_family == "Debian"
      - inventory_hostname in groups["mtaServers"]
    tags:
      - install-carbonio-mta
      
  - name: Install Carbonio MTA [RHEL]
    become: true
    ansible.builtin.yum: name={{ item }} state=present
    with_items:
      - "{{ mta_packages }}" 
    when:
      - ansible_facts.os_family == "RedHat"
      - inventory_hostname in groups["mtaServers"]
    tags:
      - install-carbonio-mta

    
     