# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
  - name: Install carbonio user management Ubuntu
    become: true
    apt: name={{ item }} state=present
    with_items:
      - "{{ carbonio_user_management_packages }}"
    when: ansible_os_family == "Debian" and inventory_hostname in groups["serviceDiscoverServers"] and (groups['filesServers'] | length > 0 or groups['taskServers'] | length > 0 or groups['workStreamServers'] | length > 0)
    tags:
      - install-carbonio-user-management

##### RHEL

  - name: Install carbonio user management RHEL
    become: true
    yum: name={{ item }} state=present
    with_items:
      - "{{ carbonio_user_management_packages }}"
    when: (ansible_os_family == "RedHat" or ansible_os_family == "CentOS") and inventory_hostname in groups["serviceDiscoverServers"] and (groups['filesServers'] | length > 0 or groups['taskServers'] | length > 0 or groups['workStreamServers'] | length > 0)
    tags:
      - install-carbonio-user-management
