# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
  - name: Install Carbonio Service discover server Ubuntu
    become: true
    apt: name={{ item }} state=present
    with_items:
      - "{{ sds_packages }}"    
    when: ansible_os_family == "Debian" and inventory_hostname in groups["serviceDiscoverServers"] 
    tags:
      - install-service-discover-server
      
  - name: Install Carbonio Service discover server RHEL
    become: true
    yum: name={{ item }} state=present
    with_items:
      - "{{ sds_packages }}"    
    when: (ansible_os_family == "RedHat" or ansible_os_family == "CentOS") and inventory_hostname in groups["serviceDiscoverServers"] 
    tags:
      - install-service-discover-server
      
   