# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
  - name: Install pgpool on Ubuntu
    become: true
    apt: name={{ item }} state=present
    with_items:
       - "{{ pgpool_packages_ubuntu }}"
    when: ansible_os_family == "Debian" and (inventory_hostname in groups["dbsConnectorServers"] and inventory_hostname not in groups["postgresServers"])
    tags:
       - install-pgpool

  - name: Install pgpool on RHEL
    become: true
    yum: name={{ item }} state=present
    with_items:
       - "{{ pgpool_packages_rhel }}"
    when: ansible_os_family == "RedHat" and (inventory_hostname in groups["dbsConnectorServers"] and inventory_hostname not in groups["postgresServers"])
    tags:
       - install-pgpool
       
  - name: Start and enable service pgpool
    ansible.builtin.systemd:
      name: pgpool-II
      state: started
      enabled: true
    when: ansible_os_family == "RedHat" and (inventory_hostname in groups["dbsConnectorServers"] and inventory_hostname not in groups["postgresServers"])
    tags:
      - install-pgpool
