# SPDX-FileCopyrightText: Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
- ansible.builtin.import_tasks: set_repos.yml
- ansible.builtin.import_tasks: set_os.yml
- ansible.builtin.import_tasks: update_os.yml
- ansible.builtin.import_tasks: minimize_swap.yml
- ansible.builtin.import_tasks: set_zextras_repos.yml
