# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
  - name: Create Postgres repo on Ubuntu
    template:
      src: postgres.list.j2
      dest: /etc/apt/sources.list.d/pgdg.list
    when: ansible_os_family == "Debian" and (inventory_hostname in groups["dbsConnectorServers"] or inventory_hostname in groups["postgresServers"])
    tags:
      - set-repos
 
  - name: Add apt key Postgres repo on Ubuntu
    become: true
    ansible.builtin.apt_key:
      url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
      state: present
    when: ansible_os_family == "Debian" and (inventory_hostname in groups["dbsConnectorServers"] or inventory_hostname in groups["postgresServers"])
    tags:
      - set-repos
       
  - name: Update repos   
    become: true
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"
    tags:
      - set-repos
       
############ RHEL        
  - name: Enable RHEL Postgres repository
    become: true
    ansible.builtin.yum:
      name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      state: present
      disable_gpg_check : true
    when: ansible_os_family == "RedHat" and (inventory_hostname in groups["dbsConnectorServers"] or inventory_hostname in groups["postgresServers"])
    tags:
      - set-repos

  - name: Disable the postgresql stream module in AppStream
    become: true
    command: '/usr/bin/dnf -qy module disable postgresql'
    when: ansible_os_family == "RedHat" and (inventory_hostname in groups["dbsConnectorServers"] or inventory_hostname in groups["postgresServers"])
    tags:
      - set-repos
       
  - name: Import EPEL GPG key
    rpm_key:
      state: present
      key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"
    tags:
      - set-repos 

  - name: Install EPEL repository package[RHEL 8]
    become: true
    ansible.builtin.yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm 
      state: present
      update_cache: yes
      disable_gpg_check: true
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"
    tags:
      - set-repos 

  - name: Install EPEL repository package[RHEL 9]
    become: true
    ansible.builtin.yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
      state: present
      update_cache: yes
      disable_gpg_check: true
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9"
    tags:
      - set-repos 

  - name: Enable powertools or crb on Rocky Linux
    become: true
    command: "{{ '/usr/bin/dnf config-manager --set-enabled powertools' if ansible_distribution_major_version == '8' else '/usr/bin/dnf config-manager --set-enabled crb' }}"
    when: ansible_distribution == "Rocky"
    tags:
      - set-repos 