# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

# Set Zextras repository

- name: Update repositories (Ubuntu)
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"
  register: update_result

- name: Check for carbonio-* packages in repositories (Ubuntu)
  command: "apt list | grep carbonio-"
  when: ansible_os_family == "Debian"
  register: carbonio_packages

- name: Verify if carbonio-* packages are found in repositories (Ubuntu)
  block:
    - name: Display list of carbonio-* packages in repositories
      debug:
        msg: "{{ carbonio_packages.stdout_lines }}"
      
    - name: Wait 10 seconds to allow users to review the output
      pause:
        seconds: 10
  when: ansible_os_family == "Debian" and carbonio_packages.stdout != ""

- name: Display notice if Zextras repository is not prepared (Ubuntu)
  block:
    - name: Display Zextras repository notice
      debug:
        msg: |
          Repository update completed successfully:
          {{ update_result }}
          
          Zextras repository is not prepared prior to installation. Carbonio will be installed using the current release version. Please consider adding the Zextras repository to ensure access to the latest updates.

    - name: Wait 10 seconds to allow users to review the notice
      pause:
        seconds: 10
  when: ansible_os_family == "Debian" and carbonio_packages.stdout == ""

- name: Copy Zextras repository for Ubuntu
  become: true
  ansible.builtin.template:
    src: zextras.list.j2
    dest: /etc/apt/sources.list.d/zextras.list
  when: ansible_os_family == "Debian" and carbonio_packages.stdout == ""

- name: Add apt key by id from a keyserver [Ubuntu 20]
  become: true
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: '{{ repo_key }}'
  when: ansible_os_family == "Debian" and ansible_distribution_major_version == "20" and carbonio_packages.stdout == ""

- name: Add apt gpg key [Ubuntu 22] or [Ubuntu 24]
  become: true
  shell: "wget -O- 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x52FD40243E584A21' | gpg --dearmor | sudo tee /usr/share/keyrings/zextras.gpg > /dev/null"
  when: ansible_os_family == "Debian" and (ansible_distribution_major_version == "22" or ansible_distribution_major_version == "24") and carbonio_packages.stdout == ""

- name: Update repos Ubuntu  
  become: true
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

############ RHEL ############

- name: Update repositories (RHEL)
  yum:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"
  register: update_result

- name: Check for carbonio-* packages in repositories (RHEL)
  command: "yum list available | grep carbonio-"
  when: ansible_os_family == "RedHat"
  register: carbonio_packages

- name: Verify if carbonio-* packages are found in repositories (RHEL)
  block:
    - name: Display list of carbonio-* packages in repositories
      debug:
        msg: "{{ carbonio_packages.stdout_lines }}"
      
    - name: Wait 10 seconds to allow users to review the output
      pause:
        seconds: 10
  when: ansible_os_family == "RedHat" and carbonio_packages.stdout != ""

- name: Display notice if Zextras repository is not prepared (RHEL)
  block:
    - name: Display Zextras repository notice
      debug:
        msg: |
          Repository update completed successfully:
          {{ update_result }}
          
          Zextras repository is not prepared prior to installation. Carbonio will be installed using the current release version. Please consider adding the Zextras repository to ensure access to the latest updates.

    - name: Wait 10 seconds to allow users to review the notice
      pause:
        seconds: 10
  when: ansible_os_family == "RedHat" and carbonio_packages.stdout == ""

- name: Copy Zextras repository for RHEL
  become: true
  ansible.builtin.template:
    src: zextras.repo.j2
    dest: /etc/yum.repos.d/zextras.repo
  when: ansible_os_family == "RedHat" and carbonio_packages.stdout == ""

- name: Install galaxy4 package repository [RHEL 8]
  become: true
  ansible.builtin.yum:
    name: http://galaxy4.net/repo/galaxy4-release-8-current.noarch.rpm
    state: present
    update_cache: yes
    disable_gpg_check: true
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8" and ansible_distribution != "Rocky"

- name: Install EPEL repository package [RHEL 8]
  become: true
  ansible.builtin.yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm 
    state: present
    update_cache: yes
    disable_gpg_check: true
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8" and ansible_distribution != "Rocky"
 
- name: Install galaxy4 package repository [RHEL 9]
  become: true
  ansible.builtin.yum:
    name: http://galaxy4.net/repo/galaxy4-release-9-current.noarch.rpm
    state: present
    update_cache: yes
    disable_gpg_check: true
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9" and ansible_distribution != "Rocky"

- name: Install EPEL repository package [RHEL 9]
  become: true
  ansible.builtin.yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    state: present
    update_cache: yes
    disable_gpg_check: true
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9" and ansible_distribution != "Rocky"

- name: Update repos RHEL  
  become: true
  yum:
    update_cache: yes
  when: ansible_os_family == "RedHat"