# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
# tasks file to prepare
   - name: Install dependencies Ubuntu
     become: true
     ansible.builtin.apt:
      pkg:
       - libgmp10
       - sysstat
       - fontconfig
       - curl
       - wget
       - sysstat
       - jq
       - python3-psycopg2
     when: ansible_os_family == "Debian"
     tags:
        - set-os  
        
   - name: Install dependencies RHEL
     become: true
     ansible.builtin.yum:
      pkg:
       - sysstat
       - fontconfig
       - dos2unix
       - curl
       - wget
       - nmap-ncat
       - sysstat
       - jq
       - python3-psycopg2
     when: ansible_os_family == "RedHat"
     tags:
        - set-os 
       
   - name: Create alias for z
     become: true
     lineinfile:
      path: /root/.bashrc
      line: alias z='su - zextras'
     tags:
        - set-os 
