collections:
  # Install a collection from Ansible Galaxy.
  - name: community.postgresql
    version: ">=3.4.0"
    source: https://galaxy.ansible.com
  - name: ansible.posix
    version: ">=1.5.4"
    source: https://galaxy.ansible.com