# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
# minimize SWAP for VMs
  - name: Minimize SWAP
    become: true
    ansible.posix.sysctl:
      name: vm.swappiness
      value: '1'
      state: present