# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
# handlers file for prepare-carbonio-vms
  - name: Restart NetworkManager
    ansible.builtin.service:
      name: NetworkManager
      state: restarted      