
# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
# tasks file for single_server_setup

  - ansible.builtin.import_tasks: execute-carbonio-reconfig.yml
  - ansible.builtin.import_tasks: disable-units.yml