
# SPDX-FileCopyrightText: Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
- ansible.builtin.import_tasks: execute_carbonio_reconfig.yml
- ansible.builtin.import_tasks: disable_units.yml