# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
  - name: Install Carbonio Video Server Ubuntu
    become: true
    apt: name={{ item }} state=present
    with_items:
      - "{{ videoserver_packages }}"
    when: ansible_os_family == "Debian"  and inventory_hostname in groups["videoServers"] 
    tags:
      - install-carbonio-videoserver
      
  - name: Install Carbonio Video Server RH
    become: true
    yum: name={{ item }} state=present
    with_items:
      - "{{ videoserver_packages }}"
    when: (ansible_os_family == "RedHat" or ansible_os_family == "CentOS") and inventory_hostname in groups["videoServers"] 
    tags:
      - install-carbonio-videoserver

    
     