# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

galaxy_info:
  author: zextras-mobius <mobius@zextras.com>
  description: Carbonio prepare for installation role
  company: zextras
  license: GPL-3.0-only

  min_ansible_version: 2.16.5

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
  - name: RHEL
    versions:
    - 8
    - 9
  - name: Ubuntu
    versions:
    - 22.04
    - 20.06

  galaxy_tags: [zextras, carbonio]

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
