# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---  
  - name: Manage Postgres password
    ansible.builtin.set_fact:
       carbonio_postgres_password: "{{ lookup('ansible.builtin.password', inventory_file + '_postgrespassword', chars=['ascii_letters', 'digits'], length=8) }}"
    when: groups['workStreamServers'] | length > 0 and inventory_hostname in groups['workStreamServers'][0] 
    tags:
      - carbonio-message-dispatcher-migration

  - name: Run carbonio-message-dispatcher-migration
    environment:
      PGPASSWORD: "{{ carbonio_postgres_password }}"
    become: true
    command: /usr/bin/carbonio-message-dispatcher-migration carbonio_adm 127.78.0.10 20000
    when: groups['workStreamServers'] | length > 0 and inventory_hostname in groups['workStreamServers'][0]
    tags:
      - carbonio-message-dispatcher-migration

  - name: Restart carbonio-message-dispatcher service
    systemd:
      name: carbonio-message-dispatcher
      state: restarted
    when: groups['workStreamServers'] | length > 0 and inventory_hostname in groups['workStreamServers'][0]
    tags:
      - carbonio-message-dispatcher-migration

  - name: Restart WSC if wsc servers > 1
    systemd:
      name: carbonio-ws-collaboration
      state: restarted
    when: groups['workStreamServers'] | length > 1 and inventory_hostname in groups['workStreamServers']
    tags:
      - carbonio-wsc-restart