# SPDX-FileCopyrightText: Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
  - name: Add and enable service-discover service
    become: true
    become_method: su
    become_user: zextras
    ansible.builtin.command: '/opt/zextras/bin/carbonio prov -l ms {{ inventory_hostname }} +zimbraServiceInstalled service-discover +zimbraServiceEnabled service-discover'
    when: inventory_hostname in groups['serviceDiscoverServers']
    tags:
      - fix-config  

  - name: Add proxy address to Carbonio trusted IPs
    become: true
    become_method: su
    become_user: zextras
    ansible.builtin.command: '/opt/zextras/bin/carbonio prov -l mcf +zimbraMailTrustedIP {{ansible_facts.default_ipv4.address}}'
    when: inventory_hostname in groups['proxyServers']
    tags:
      - fix-config   

  - name: Set SMTP hostname for MTA servers
    become: true
    become_method: su
    become_user: zextras
    ansible.builtin.command: '/opt/zextras/bin/carbonio prov -l ms {{ inventory_hostname }} zimbraSmtpHostname localhost zimbraSmtpPort 25'
    when: inventory_hostname in groups['mtaServers']
    tags:
      - fix-config    
      
  - name: Configure public service hostname
    become: true
    become_method: su
    become_user: zextras
    ansible.builtin.command: '/opt/zextras/bin/carbonio prov -l mcf zimbraPublicServiceHostname {{ hostvars[groups['proxyServers'][0]].webmailHostname }}'
    when:
      - inventory_hostname == groups['masterDirectoryServers'][0]
      - hostvars[groups['proxyServers'][0]].webmailHostname is defined
    tags:
      - fix-config