# SPDX-FileCopyrightText: Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
- ansible.builtin.import_tasks: execute_carbonio_pending_setups.yml
- ansible.builtin.import_tasks: execute_post_install_cmds.yml
- ansible.builtin.import_tasks: execute_dbconnectors_bootstrap.yml
- ansible.builtin.import_tasks: execute_config_fixes.yml
- ansible.builtin.import_tasks: restart_carbonio_appserver.yml
- ansible.builtin.import_tasks: execute_carbonio_pending_setups.yml
  when: groups['all'] | length == 1
- ansible.builtin.import_tasks: configure_videoserver.yml
