# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
- name: Make sure there is right number of Consul servers
  fail:
    msg: "The serviceDiscoverServers group requires exactly 1 or 3 servers to ensure proper leader determination and system stability. To continue, please ensure that serviceDiscoverServers group is configured correctly."
  when: "groups['serviceDiscoverServers'] | length not in [1, 3]"
  tags:
    - check-carbonio-service-discover
