- hosts: all
  order: inventory
  gather_facts: yes
  roles:
     - prepare-carbonio-vms
     - install-carbonio-packages

- hosts: masterDirectoryServers, replicaDirectoryServers, postgresServers
  serial: 1
  order: inventory
  gather_facts: yes
  roles:
     - bootstrap-cluster-services

- hosts: all, !postgresServers, !masterDirectoryServers, !replicaDirectoryServers
  serial: 1
  order: inventory
  gather_facts: yes
  roles:
     - bootstrap-cluster-services

- hosts: masterDirectoryServers, replicaDirectoryServers, postgresServers
  order: inventory
  gather_facts: yes
  roles:
     - bootstrap-carbonio
     - execute-final-setups

- hosts: all, !postgresServers, !masterDirectoryServers, !replicaDirectoryServers
  order: inventory
  gather_facts: yes
  roles:
     - bootstrap-carbonio
     - execute-final-setups
