# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
  - name: Make sure that dbsConnectorServers group is empty
    run_once: true
    delegate_to: localhost
    fail:
      msg: "dbsConnectorServers group is deprecated for Standard Carbonio Installation. To continue, please keep this group empty."
    when: groups['dbsConnectorServers'] | length > 0
    tags:
      - check-carbonio-dbconnectors
            