# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
- name: Make sure there is only one server in the masterDirectoryServers group
  fail:
    msg: "This playbook does not support multi-server Master Directory installation. To continue, please ensure there is only one Master Directory server defined in the masterDirectoryServers group."
  when: groups['masterDirectoryServers'] | length > 1
  tags:
    - check-carbonio-directory-server