# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
- ansible.builtin.import_tasks: validate_inventory_chats.yml
- ansible.builtin.import_tasks: validate_inventory_db_connectors.yml
- ansible.builtin.import_tasks: validate_inventory_service_discovery.yml
- ansible.builtin.import_tasks: validate_inventory_postgresql.yml
- ansible.builtin.import_tasks: validate_inventory_directory.yml
- ansible.builtin.import_tasks: validate_inventory_values.yml
- ansible.builtin.import_tasks: validate_inventory_single_server.yml
  when: groups["all"] | length == 1
- ansible.builtin.import_tasks: validate_ubuntu_installation.yml
- ansible.builtin.import_tasks: validate_host_fqdn.yml
- ansible.builtin.import_tasks: validate_hosts_file.yml
  
