# SPDX-FileCopyrightText: Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
# handlers file for execute-final-setups
    - name: restart_preview
      ansible.builtin.service:
        name: carbonio-preview.service
        state: restarted

    - name: restart_videoserver
      ansible.builtin.service:
        name: carbonio-videoserver.service
        state: restarted

    - name: restart_postgres-rhel
      ansible.builtin.service: name={{ postgresql_service_name }} state=restarted